### ISSUE TITLE
https://github.com/td2004/untitled-11.py.git

### ISSUE THREAD

**Issue by tcdinesh** [td2004/untitled-11.py#1]
ttttttt wwwww
last_tuesday = given_date - timedelta(days=offset)
print("The last Tuesday of the month is:", last_tuesday)
offset = (given_date.weekday())%7
last_monday = given_date - timedelta(days=offset)
print("The last Monday of the month is:", last_monday)
offset = (given_date.weekday() - 6)%7
last_sunday = given_date - timedelta(days=offset)
print("The last Saturday of the month is:", last_sunday)
birthday = ["31.03.2004" , "02.04.1978"]

for i in birthday:
    newdate = datetime.strptime(i, "%d.%m.%Y")
    newdate.strftime("%d.%m.%Y %H:%M:%S")
    if given_date==newdate:
        print(i, "is a Birthday")
    else:
        print("has nothing important")
        
import pandas as pd

data = {'': ['laptop', 'printer', 'tablet', 'desk', 'chair'],
        'price': [1200, 150, 300, 450, 200]
        }

df = pd.DataFrame(data, index=['product_1','product_2','product_3','product_4','product_5'])

print (df)

**Comment by td2004** [comment]
hi

**Comment by tcdinesh** [comment]
hi
